#!/bin/bash
BIN_DIR = $HOME/realwork/github/llvm-project-prepo/build_mac/Release/bin
WORK_DIR = $HOME/gen/output

./index.js \
           --linker=lld \
           --output=./results/lld.dat \
           --force \
           --work-dir=$WORK_DIR \
           --bin-dir=$BIN_DIR \
           --linkonce=1000 \
           --external=1000 \
           --increment=100 \
           --modules=10
gnuplot plot < ./results/lld.dat > ./results/lld.svg

./index.js \
           --linker=rld \
           --output=./results/rld.dat \
           --force \
           --work-dir=$WORK_DIR \
           --bin-dir=$BIN_DIR \
           --linkonce=1000 \
           --external=1000 \
           --increment=100 \
           --modules=10
gnuplot plot < ./results/rld.dat > ./results/rld.svg
