#!/bin/bash
BIN_DIR=$HOME/realwork/github/llvm-project-prepo/build_mac/Release/bin
WORK_DIR=$HOME/gen/output
LINKONCE=1000
EXTERNAL=1000
INCREMENT=100
MODULES=10

echo "Timing lld"
./index.js \
           --linker=lld \
           --output=./results/lld.csv \
           --force \
           --work-dir=$WORK_DIR \
           --bin-dir=$BIN_DIR \
           --linkonce=$LINKONCE \
           --external=$EXTERNAL \
           --increment=$INCREMENT \
           --modules=$MODULES
gnuplot plot < ./results/lld.csv > ./results/lld.svg

echo "Timing rld"
./index.js \
           --linker=rld \
           --output=./results/rld.csv \
           --force \
           --work-dir=$WORK_DIR \
           --bin-dir=$BIN_DIR \
           --linkonce=$LINKONCE \
           --external=$EXTERNAL \
           --increment=$INCREMENT \
           --modules=$MODULES
gnuplot plot3d < ./results/rld.csv > ./results/rld.svg

./comparison.js --major=external --minor=linkonce ./results/lld.csv ./results/rld.csv > ./results/external.csv
./comparison.js --major=linkonce --minor=external ./results/lld.csv ./results/rld.csv > ./results/linkonce.csv
