#!/bin/bash
set -e # exit upon non-zero exit from a command
#set -x # print commands as they're executed
set -u # substituting an unset variable is an error

./update-readme.js "$HOME/prepo" > ./results/README.md
